language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: SnhwqAqJR9HyJmJ0/NVFmn8bITT0GtltwymgF72RVgR15FuPE5Gqcz4c0Pga71+k8B6pF6JMyqLOKE5uAIKCVIaDdhOflySw6sdTGDX4JK2wNnHvMQsUmcYeyzrF6rdJdz3hEX2Uyfq2lnI4tM60esuNqb2b5OqatfY3/ccia7JKLlen+wxwDA9zHLKw7rU7pLvl1MoxBJXkfgQ2z/mIzU3HGIMA8rcVsKvKYZT97KIOqZzRgNSKmcZUy6Q3B716kyu6hQmsVezQL3FYakq+OGgB8zvJ6Www4FGwgqBZuLbX5o4cFuXG9lQHxJlVj9P9pPV82pK4qdClIoARuW5c1Kc0K4IWmbcp6l+PzNtwXQHYjziYLGMAjbo/Mjetxa8F8bX24bU5rk0/1I0nu/cy3c3lnwaFJ0rBv2qR6w3u6XlbIW6QvZjDF24E7+LD2QjPoWPcOklHcZvNTHURvAW6cDxxkE/izfuaHfd17z+1WLLyKQtEBKpRCf+aGVEiR6LZ4nNqdjUJG+bxAxus5c7Z2wFyDVTluyDDehmil8QgALIpowR2rB6RpmVz90uZ/40H/ru8FKKTfT0Qb5dU3guhsGf7EAKrnpEpi9t3prkePC7rH1WmvgBoLftzXrzc2gymM6zSJNpNn5KzX0MIXluBRu6MlXbVh/wdZ29O94OQKyU=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: mqpujKFDFC6tsoII/5pOm8BEBBv/oW+RsclcrHnpnAMHYbvZUEnD29jTCWaR285G1PXSct5tpRcaj0C97oCprh8gUcrRN1T4Ddfb5c17vbxFQYkcxZ/OhRJXvAkIz5q6Y2X0pleKgJ2rlKKiiqGSWtEsnezAf5iMOEOHaUmiwlIiaMGcPjkEoTVTTnqcHNCpnNr59/bv2V6bDfQg6w4udHGR8Mx9ADyLzDjXRGmC7v8eeJPNroXWqgWFzzUlUdbPHiSBIVda70UZXA6Hv4rsPdgza/pT0MFcuR2nFTUcUDo18aUEGZPZ1IpO98kbsSRZZd/YYcn/uin1HVPy7Q7REUVgn5batssvDDh/oq5ZrZ2sU7SgBv0OZk/qTjQkmCRZXG8rW5uRsVNaXGBEr4ZJqZeWA+SV5PXeniX2MonRDSj5cVNEcY9F4aG42BXmiPUTlvl1sAgg9Z5Bhypcj2IemxDAUSHrJM+7Oy9893R1KnvCB86W5HKP11PZ3xS7sWbRsJdXaGDaulRfH4rzUnpXbH9ow76YvkXfgG+jKxBJGqahBhKPx4z6dO93/9eZQRtcWHZq1Og/R/fDVYGTYKQFFhSexxKopPvUSLWjRusOfTS+RpfuIEBWtR3EMXXAzyci6kJUJMPomB9BcNjmA5orULJtNqOezjHRMx377AsuN+A=
sudo: false
