language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: stTO1TcGy2XKqGHfZM2PdKTG45zA4Xb+sAwRBcQVysjLmStvFm0DR2MLxXt9basGHx8y2lTpRlQ8OXQWB5paDlwuAt21nImhk5FW39OVkLN933/Q2YwLCZ+O4cv8u7TxrRz76b/ZeCCxoXepfnUlAQrWGidtoSxljPNoxHBSDp8ufKnXtCJkES0AlFQEjDA4fq0zenlfbH52fK3bZ/A5HYsGOcMW6hd0O3vNGuLoj6L0K4wZqxJcvVJApAQF0DOETLrh8iKQbnIVUsVuTSUCzsZDiUi5Hw2TFXlVUykdGFDrVSW6SjwHEsZBhLcBOkJ+2R0uNg3JeNX5w5kcQvMzY2qr3up4HjlGKqDZLIjle1ldhphuuer8bFWx7kWFQdko5ZKOwJk4E95ixfIxZQ/jW97YcqCjFCeCVy0Wa2p9iMMBl/YG4spFAhCEvhz0ZRMpKeWuEq9mNAta1igseG3czmUH2mW2+/sVe/KibO3lXRtRAtzX8hag1wR5nGAHxXw1B5jVX3TcvVLHDyD9U2/bfV0qt8/Kff4g6xWnQE+xNMjlrOBOuNqyP/r+ycpSD6Q2A+PMC15aFYcsQjxFTfMxM1Ha9IWGvCBpHzEO3SQNl/5ok8dIoN5uqbWVYcbES2+Xf5qk7mWfw6ZL45fwwGDKvvHhz+Qe7VJmYLyMvALTmYo=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: HGleBiDKX+Rjb1IR4N2bcR/Hs+yuXs69TwIFIzKZOU3TRRNwRj+4y3w6K4s9xL3LzhnBKbq40UqJkirF3MC95f3fHhLiXpLRx365OTUeMFXrnzoerbEiZwXZb5QwzLCmtN3yWy29jOjmd7m/mhDY414aYtmprH/q1/T3uWkGenROcy/FgS2Dy3IP4eMzwAcSob6k8QG+cCrjegeWggzzMMGKxaVS3mFRXBmwf/4WvuoRlQDBByucnKcVIJE1sjwliqpLPTx27S1DkqzhaCLd+IozBeKAawQM8QFJBVa7slcOP98LHhL0gSWAqVBsWWMH9gz9peBN0KBfh5dDDf67q3cfwxqhmaKR+qBjJvXQPE5HGearwr/gbTD0YgEPw2uwnEpWhSxEgXEDV/zShhsqH7sDzTuNfT5ktWmLryMePOcriwfoKw3sVdf8ZT/wZM/+1brZ9Q614y2wxKN4JAmWosw60a8PfX6SDJlKQQ0bwGJWppolpK135DE7PqzBw+HxWWki3ga6YjWDb6zviMQZGxxNKfC0AgfPbYAN9wA/Jfx7HheGcSYdEPHZTRF0G/4LQMHStD9Ss5YKb1ocNMlnxjVMU0sl/hXlkTvAjTQaCVzZSak6l2CuptoOAFl67ZkbocdJ+0qIQhvSHjdP619tbvYY5eyimhaOHY8wN6Z6Y74=
sudo: false
